config/routes.rb
Rails.application.routes.draw do

  root 'welcomes#index'

  devise_for :users, controllers: {
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  namespace :users do
    resource :account, only: [:show, :edit, :update]
    resource :digest, only: [:show]
  end

  resources :motions, controller: 'motion/motions'

  namespace :motion do
    resources :fronts
    resources :responses
    resources :comments
    resources :replies
    resource :rating
  end

  resource :search, only: [:show]

  get 'tests/index'

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :manage_root_view

  def index
    @user = User.new
    @devise_mapping = Devise.mappings[:user]
  end

  private
  def manage_root_view
    (redirect_to users_digest_path) if current_user
  end
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    resource.class
  end
end

app/views/welcomes/index.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="row">
      <%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2), class: "btn btn-danger btn-lg col-md-offset-2 col-md-10" %>
    </div>
    <br>
    <div class="row">
      <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), class: "btn btn-primary btn-lg col-md-offset-2 col-md-10" %>
    </div>
    <br>
    <div class="row">
      <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter), class: "btn btn-info btn-lg col-md-offset-2 col-md-10" %>
      <!-- <a href="#" class="btn btn-info btn-lg col-md-offset-2 col-md-10 disabled">Sign in with Twitter<h6><em>Coming Soon</em></h6></a> -->
    </div>
    <br>

  </div>
  <div class="col-md-6">

    <%= form_for(resource, as: resource_name, url: session_path(resource_name),
                html: { class: 'form-horizontal' }) do |f| %>
      <div class="field form-group">
        <%= f.label :login, class: 'col-md-3 control-label' %>
        <div class="col-md-7">
          <%= f.text_field :login, autofocus: true, class: 'form-control' %>
        </div>
      </div>

      <div class="field form-group">
        <%= f.label :password, class: 'col-md-3 control-label' %>
        <div class="col-md-7">
          <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
        </div>
      </div>

      <% if devise_mapping.rememberable? -%>
        <div class="field form-group">
          <div class="col-sm-offset-3 col-sm-9">
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me %>
          </div>
        </div>
      <% end -%>

      <div class="actions form-group">
        <div class="col-sm-offset-3 col-sm-9">
          <%= f.submit "Log in", class: 'btn btn-success' %>
        </div>
      </div>
    <% end %>

    <div class="col-sm-offset-3 col-sm-9">
      <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
        <%= link_to "Sign up", new_registration_path(resource_name) %><br />
      <% end -%>

      <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
        <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
      <% end -%>

      <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
        <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
      <% end -%>

      <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
        <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
      <% end -%>
    </div>


  </div>
</div>