config/routes.rb
Rails.application.routes.draw do

  root 'welcomes#index'

  devise_for :users, controllers: {
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  namespace :users do
    resource :account, only: [:show, :edit, :update]
    resource :digest, only: [:show]
  end

  resources :motions, controller: 'motion/motions'

  namespace :motion do
    resources :fronts
    resources :responses
    resources :comments
    resources :replies
    resource :rating
  end

  resource :search, only: [:show]

  get 'tests/index'

end

app/models/motion.rb
class Motion < ActiveRecord::Base

  validates :subject, :description, :user, presence: true
  belongs_to :user
  has_many :fronts, dependent: :destroy
  has_many :responses

  has_many :rating, as: :rateable
  has_many :mentions, as: :mentionable

  after_create :create_default_fronts, if: :default_fronts_enabled
  after_create :create_common_front, unless: :default_fronts_enabled

  private
    def create_default_fronts
      fronts.create(name: 'For', category: 0, user: user, description: 'Towards the motion')
      fronts.create(name: 'Against', category: 1, user: user, description: 'Against the motion')
      fronts.create(name: 'Neutral', category: 2, user: user, description: 'Balanced for either For/Against perspective of the motion')
    end

    def create_common_front
      fronts.create(name: 'Common Motion', category: 4, user: user, description: 'Common front')
    end

end

app/controllers/motion/comments_controller.rb
class Motion::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_response, only: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.response = @response
    @comment.user = current_user
    if @comment.save
      redirect_to motion_response_path(@response), success: 'Comment added successfully'
    else
      redirect_to motion_response_path(@response)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:description)
  end

  def fetch_response
    @response = Response.find_by(id: params[:response])
  end
end

app/controllers/motion/fronts_controller.rb
class Motion::FrontsController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_motion, only: [:new, :create]
  before_action :motion_allows_front_creation?, only: [:new, :create]

  def new
    @front = Front.new
  end

  def create
    @front = Front.new(motion_params.merge(user: current_user))
    @front.motion = @motion
    @front.front_category = :custom
    if @front.save
      redirect_to motion_path(@front.motion), success: 'Front created successfully'
    else
      render :new
    end
  end

  private

  def motion_params
    params.require(:front).permit(:name, :motion)
  end

  def fetch_motion
    @motion = Motion.find_by(id: params[:m])
    (redirect_to :back, alert: 'Motion not found!') unless @motion
  end

  def motion_allows_front_creation?
    (redirect_to :back, alert: 'Invalid request!') unless @motion.multiple_fronts_enabled
  end
end

app/controllers/motion/motions_controller.rb
require 'engtagger'

class Motion::MotionsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :fetch_motion, only: [:edit, :update, :show]
  before_action :authenticate_user_for_edit, only: [:edit, :update]

  after_action :populate_tags, only: [:create, :update]

  def index
    @motions = Motion.where(user: current_user).order(created_at: :desc)
  end

  def show
    @for_front = @motion.fronts.where(category: 0).limit(1).first
    @against_front = @motion.fronts.where(category: 1).limit(1).first
    @neutral_front = @motion.fronts.where(category: 2).limit(1).first
    @common_front = @motion.fronts.where(category: 4).limit(1).first
    @response = Response.new
  end

  def new
    @motion = Motion.new
  end

  def create
    @motion = Motion.new(motion_params.merge(user: current_user))
    if @motion.save
      redirect_to motion_path(@motion), success: 'Motion created successfully'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @motion.update(motion_params)
      redirect_to motion_path(@motion), success: 'Motion saved successfully'
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def motion_params
    params.require(:motion).permit(:subject, :description, :default_fronts_enabled, :multiple_fronts_enabled)
  end

  def fetch_motion
    @motion = Motion.find_by(id: params[:id])
  end

  def authenticate_user_for_edit
    if current_user && @motion.user.id != current_user.id
      redirect_to :back, alert: 'Access Denied'
    end
  end

  def populate_tags
    tagger = EngTagger.new
    tagged = tagger.add_tags(ActionView::Base.full_sanitizer.sanitize(@motion.description))
    proper_nouns_of_description = tagger.get_proper_nouns(tagged)
    tagged = tagger.add_tags(@motion.subject)
    nouns_from_subject = tagger.get_noun_phrases(tagged)
    ActiveRecord::Base.transaction do
      persist_tags(proper_nouns_of_description)
      persist_tags(nouns_from_subject)
    end
  end

  def persist_tags(tags_hash)
    tags_hash.each do |k, v|
      t = Tag.find_or_initialize_by(name: k)
      t.day_hitpoints = t.day_hitpoints ? t.day_hitpoints + v : v
      t.save
    end
  end
end

app/controllers/motion/ratings_controller.rb
class Motion::RatingsController < ApplicationController
  before_action :authenticate_user!
  before_action :resolve_ratebale, only: [:create]

  def create
    if @rateable
      if !@rateable.rating.where(user: current_user).exists?
        @rating = @rateable.rating.build(rating_value: 1, user: current_user)
        @rating.save
        @cls_name = 'btn btn-xs btn-warning'
      else
        @rateable.rating.where(user: current_user)[0].destroy
        @cls_name = 'btn btn-xs btn-default'
      end
      @element_identifier_class = "#{@rateable.class.to_s.downcase}-#{@rateable.id}-upvote-count"
      @upvotes = @rateable.rating.count
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:rating_value)
  end

  def resolve_ratebale
    if params[:motion_id]
      @rateable = Motion.find(params[:motion_id])
    elsif params[:response_id]
      @rateable = Response.find(params[:response_id])
    elsif params[:comment_id]
      @rateable = Comment.find(params[:comment_id])
    elsif params[:reply_id]
      @rateable = Reply.find(params[:reply_id])
    end
  end
end

app/controllers/motion/replies_controller.rb
class Motion::RepliesController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_comment, only: [:create]

  def create
    @reply = Reply.new(reply_params)
    @reply.comment = @comment
    @reply.user = current_user
    if @reply.save
      redirect_to motion_response_path(@comment.response), success: 'reply added successfully'
    else
      redirect_to motion_response_path(@comment.response)
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:description)
  end

  def fetch_comment
    @comment = Comment.find_by(id: params[:comment])
  end
end

app/controllers/motion/responses_controller.rb
class Motion::ResponsesController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_front, only: [:create, :update]
  before_action :fetch_response, only: [:show, :destroy]
  before_action :fetch_response_for_update, only: [:update]

  def show
    @front = @response.front
    @motion = @response.motion
    @all_responses = @front.responses.reject{ |r| r.id == @response.id }
    @comment = @response.comments.build(user: current_user)
    @reply = Reply.new
  end

  def create
    @response = Response.new(response_params)
    @response.front = @front
    @response.motion = @front.motion
    @response.user = current_user
    if @response.save
      redirect_to motion_path(@response.motion), success: 'Response added successfully'
    else
      redirect_to motion_path(@response.motion)
    end
  end

  def edit
  end

  def update
    if @response.user.id == current_user.id &&
        @response.front.id == @front.id &&
        @response.update(response_params)
      redirect_to motion_path(@response.motion), success: 'Response saved successfully'
    else
      redirect_to motion_path(@response.motion)
    end
  end

  def destroy
    motion = @response.motion
    @response.destroy
    redirect_to motion_path(motion), success: 'Response deleted successfully'
  end

  private

  def response_params
    params.require(:response).permit(:description)
  end

  def fetch_front
    @front = Front.find_by(id: params[:front])
  end

  def fetch_response
    @response = Response.find_by(id: params[:id])
  end

  def fetch_response_for_update
    @response = Response.find_by(id: params[:response][:id])
  end
end

app/views/motion/motions/_front_with_responses.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <span><%= front.name %></span>
    </div>
    <% unless front.responses.exists? %>
      <span class="pull-right label label-info">No response related to this front</span>
    <% end %>
  </div>
  <div class="panel-body">
    <% unless current_user && motion.responses.where(user: current_user).exists? %>
      <%= form_for(response, url: motion_responses_path(front: front.id), html: { method: :post, class: 'form-inline' }) do |f| %>

        <%= f.text_area :description, class: 'form-control input-sm textarea-create-response', placeholder: 'Register your response', required: true %>
        <span><%= f.submit 'Enter', class: 'btn btn-success btn-xs' %></span>
      <% end %>
      <br>
    <% end %>

    <% front.responses.each do |r| %>
      <%= render partial: 'responses', locals: { response: r, front: front } %>
    <% end %>
  </div>
</div>

app/views/motion/motions/_new_response_modal.html.erb
<%= form_for(response, url: motion_responses_path(front: front.id), html: { method: :post, class: 'form-inline' }) do |f| %>

  <%= f.text_area :description, class: 'form-control input-sm textarea-create-response', placeholder: 'Register your response', required: true %>
  <span><%= f.submit 'Enter', class: 'btn btn-success btn-xs' %></span>
<% end %>

app/views/motion/motions/_responses.html.erb
<div id="<%= "#{response.user.username}-response" %>" class="well well-sm response-container">

  <% if current_user && response.user.id == current_user.id -%>
  <div class="hover-info">
    <!-- Trigger the modal with a button -->
    <a data-toggle="modal" data-target="#edit-form">Edit</a>
    <%= link_to 'View', motion_response_path(response) %>
  </div>

  <!-- Modal -->
  <div id="edit-form" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><%= response.description.html_safe %></h4>
        </div>
        <div class="modal-body">
          <%= form_for(response, url: motion_response_path(front: front.id), html: { method: :patch, class: 'form-group' }) do |f| %>

            <%= f.hidden_field :id, value: response.id %>
            <%= f.text_area :description, rows: 6, class: 'form-control input-sm textarea-edit-response', placeholder: 'Register your response', required: true %>
            <br>
            <%= f.submit 'Update', class: 'btn btn-success btn-sm update-response-button' %>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

  <% else %>
    <div class="hover-info">
      <div class="rating">
        <%= button_to motion_rating_path(response_id: response.id), remote: true, method: :post, class: "btn btn-xs btn-#{response.rating.where(user: current_user).exists? ? 'warning' : 'default'}" do %>
          Upvote <span class="badge response-<%= response.id %>-upvote-count"><%= response.rating.count %></span>
        <% end %>
      </div>
      <%= link_to 'Interject', motion_response_path(response) %>
    </div>

  <% end -%>

<%= response.description.html_safe %>
</div>

app/views/motion/motions/edit.html.erb
<%= javascript_include_tag 'wysiwyg_manager' %>

<h1>Edit Motion</h1>

<%= form_for(@motion, url: motion_path, html: { method: :patch, class: 'form-horizontal' }) do |f| %>
  <div class="form-group">
    <%= f.label :subject, class: 'col-md-3 control-label' %>
    <div class="col-md-7">
      <%= f.text_field :subject, autofocus: true, class: 'form-control' %>
    </div>
  </div>
  <br>

   <div class="form-group">
    <label class="col-md-3 control-label">Fronts Options</label>

    <%= f.label :default_fronts_enabled, 'Create Default fronts(For, Neutral, Against) with motion?', class: 'col-md-3 col-md-offset-0' %>
    <div class="col-md-1">
      <div class="slideThree" style="margin: 10px auto;">
        <%= f.check_box :default_fronts_enabled, class: 'form-control' %>
        <label for="motion_default_fronts_enabled"></label>
      </div>
    </div>

    <%= f.label :multiple_fronts_enabled, 'Allow users to create multiple fronts?', class: 'col-md-3 col-md-offset-1' %>
    <div class="col-md-1">
      <div class="slideThree" style="margin: 10px auto;">
        <%= f.check_box :multiple_fronts_enabled, class: 'form-control' %>
        <label for="motion_multiple_fronts_enabled"></label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.text_area :description, rows: 10, class: 'form-control wysiwyg-textbox' %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit "Update", class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/motion/motions/index.html.erb
<h2>My motions</h2>

<% @motions.each do |m| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
        <%= link_to m.subject, motion_path(m) %>
      </h3>
      <div class="pull-right">
        &nbsp;<%= m.user.account_picture? ? image_tag(m.user.account_picture_url(:thumb)) : image_tag('default-dp.png', width: 50) %>
      </div>
      <div class="pull-right">
        <span class="badge">
          <%= "#{m.user.username}, #{m.created_at.strftime('%B %d, %Y | %I:%M %p')}" %>
        </span>
      </div>
    </div>
    <div class="panel-body">
      <%= m.description.html_safe %>
      <em><%= link_to 'Read More', motion_path(m) %></em>
    </div>
  </div>
<% end %>

app/views/motion/motions/new.html.erb
<%= javascript_include_tag 'wysiwyg_manager' %>

<h1>Create Motion</h1>

<%= form_for(@motion, url: motions_path, html: { class: 'form-horizontal' }) do |f| %>
  <div class="form-group">
    <%= f.label :subject, class: 'col-md-3 control-label' %>
    <div class="col-md-7">
      <%= f.text_field :subject, autofocus: true, class: 'form-control' %>
    </div>
  </div>
  <br>

  <div class="form-group">
    <label class="col-md-3 control-label">Fronts Options</label>

    <%= f.label :default_fronts_enabled, 'Create Default fronts(For, Neutral, Against) with motion?', class: 'col-md-3 col-md-offset-0' %>
    <div class="col-md-1">
      <div class="slideThree" style="margin: 10px auto;">
        <%= f.check_box :default_fronts_enabled, class: 'form-control', checked: true %>
        <label for="motion_default_fronts_enabled"></label>
      </div>
    </div>

    <%= f.label :multiple_fronts_enabled, 'Allow users to create multiple fronts?', class: 'col-md-3 col-md-offset-1' %>
    <div class="col-md-1">
      <div class="slideThree" style="margin: 10px auto;">
        <%= f.check_box :multiple_fronts_enabled, class: 'form-control' %>
        <label for="motion_multiple_fronts_enabled"></label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.text_area :description, rows: 10, class: 'form-control wysiwyg-textbox' %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit "Create", class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/motion/motions/show.html.erb
<%= javascript_include_tag 'details_on_hover_manager' %>

<%= render partial: '/motion/motions', locals: { motion: @motion } %>

<% if current_user && @motion.responses.where(user: current_user).exists? %>
  <p class="label label-info">
    You have already registered your response. You can edit it <a href="#<%= "#{current_user.username}-response" %>">here</a>
  </p>
<% end %>
<br><br>

<% if @motion.multiple_fronts_enabled %>
  <span class="pull-right add-front-plus-sign">
    <%= link_to '', new_motion_front_path(m: @motion.id), class: 'btn btn-default btn-sm glyphicon glyphicon-plus', title: 'Add new front', :'data-toggle' => "tooltip", :'data-placement' => "left" %>
  </span>
<% end %>

<div class="motion-fronts">
  <div class="fronts-wrapper">
  <% @motion.fronts.each do |f| %>
    <div class="fronts">
      <%= render partial: 'front_with_responses', locals: {front: f, response: @response, motion: @motion} %>
    </div>
  <% end %>
  </div>

</div>