config/routes.rb
Rails.application.routes.draw do

  root 'welcomes#index'

  devise_for :users, controllers: {
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  namespace :users do
    resource :account, only: [:show, :edit, :update]
    resource :digest, only: [:show]
  end

  resources :motions, controller: 'motion/motions'

  namespace :motion do
    resources :fronts
    resources :responses
    resources :comments
    resources :replies
    resource :rating
  end

  resource :search, only: [:show]

  get 'tests/index'

end

app/models/motion.rb
class Motion < ActiveRecord::Base

  validates :subject, :description, :user, presence: true
  belongs_to :user
  has_many :fronts, dependent: :destroy
  has_many :responses

  has_many :rating, as: :rateable
  has_many :mentions, as: :mentionable

  after_create :create_default_fronts, if: :default_fronts_enabled
  after_create :create_common_front, unless: :default_fronts_enabled

  private
    def create_default_fronts
      fronts.create(name: 'For', category: 0, user: user, description: 'Towards the motion')
      fronts.create(name: 'Against', category: 1, user: user, description: 'Against the motion')
      fronts.create(name: 'Neutral', category: 2, user: user, description: 'Balanced for either For/Against perspective of the motion')
    end

    def create_common_front
      fronts.create(name: 'Common Motion', category: 4, user: user, description: 'Common front')
    end

end

app/controllers/motion/comments_controller.rb
class Motion::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_response, only: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.response = @response
    @comment.user = current_user
    if @comment.save
      redirect_to motion_response_path(@response), success: 'Comment added successfully'
    else
      redirect_to motion_response_path(@response)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:description)
  end

  def fetch_response
    @response = Response.find_by(id: params[:response])
  end
end

app/controllers/motion/fronts_controller.rb
class Motion::FrontsController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_motion, only: [:new, :create]
  before_action :motion_allows_front_creation?, only: [:new, :create]

  def new
    @front = Front.new
  end

  def create
    @front = Front.new(motion_params.merge(user: current_user))
    @front.motion = @motion
    @front.front_category = :custom
    if @front.save
      redirect_to motion_path(@front.motion), success: 'Front created successfully'
    else
      render :new
    end
  end

  private

  def motion_params
    params.require(:front).permit(:name, :motion)
  end

  def fetch_motion
    @motion = Motion.find_by(id: params[:m])
    (redirect_to :back, alert: 'Motion not found!') unless @motion
  end

  def motion_allows_front_creation?
    (redirect_to :back, alert: 'Invalid request!') unless @motion.multiple_fronts_enabled
  end
end

app/controllers/motion/motions_controller.rb
require 'engtagger'

class Motion::MotionsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :fetch_motion, only: [:edit, :update, :show]
  before_action :authenticate_user_for_edit, only: [:edit, :update]

  after_action :populate_tags, only: [:create, :update]

  def index
    @motions = Motion.where(user: current_user).order(created_at: :desc)
  end

  def show
    @for_front = @motion.fronts.where(category: 0).limit(1).first
    @against_front = @motion.fronts.where(category: 1).limit(1).first
    @neutral_front = @motion.fronts.where(category: 2).limit(1).first
    @common_front = @motion.fronts.where(category: 4).limit(1).first
    @response = Response.new
  end

  def new
    @motion = Motion.new
  end

  def create
    @motion = Motion.new(motion_params.merge(user: current_user))
    if @motion.save
      redirect_to motion_path(@motion), success: 'Motion created successfully'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @motion.update(motion_params)
      redirect_to motion_path(@motion), success: 'Motion saved successfully'
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def motion_params
    params.require(:motion).permit(:subject, :description, :default_fronts_enabled, :multiple_fronts_enabled)
  end

  def fetch_motion
    @motion = Motion.find_by(id: params[:id])
  end

  def authenticate_user_for_edit
    if current_user && @motion.user.id != current_user.id
      redirect_to :back, alert: 'Access Denied'
    end
  end

  def populate_tags
    tagger = EngTagger.new
    tagged = tagger.add_tags(ActionView::Base.full_sanitizer.sanitize(@motion.description))
    proper_nouns_of_description = tagger.get_proper_nouns(tagged)
    tagged = tagger.add_tags(@motion.subject)
    nouns_from_subject = tagger.get_noun_phrases(tagged)
    ActiveRecord::Base.transaction do
      persist_tags(proper_nouns_of_description)
      persist_tags(nouns_from_subject)
    end
  end

  def persist_tags(tags_hash)
    tags_hash.each do |k, v|
      t = Tag.find_or_initialize_by(name: k)
      t.day_hitpoints = t.day_hitpoints ? t.day_hitpoints + v : v
      t.save
    end
  end
end

app/controllers/motion/ratings_controller.rb
class Motion::RatingsController < ApplicationController
  before_action :authenticate_user!
  before_action :resolve_ratebale, only: [:create]

  def create
    if @rateable
      if !@rateable.rating.where(user: current_user).exists?
        @rating = @rateable.rating.build(rating_value: 1, user: current_user)
        @rating.save
        @cls_name = 'btn btn-xs btn-warning'
      else
        @rateable.rating.where(user: current_user)[0].destroy
        @cls_name = 'btn btn-xs btn-default'
      end
      @element_identifier_class = "#{@rateable.class.to_s.downcase}-#{@rateable.id}-upvote-count"
      @upvotes = @rateable.rating.count
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:rating_value)
  end

  def resolve_ratebale
    if params[:motion_id]
      @rateable = Motion.find(params[:motion_id])
    elsif params[:response_id]
      @rateable = Response.find(params[:response_id])
    elsif params[:comment_id]
      @rateable = Comment.find(params[:comment_id])
    elsif params[:reply_id]
      @rateable = Reply.find(params[:reply_id])
    end
  end
end

app/controllers/motion/replies_controller.rb
class Motion::RepliesController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_comment, only: [:create]

  def create
    @reply = Reply.new(reply_params)
    @reply.comment = @comment
    @reply.user = current_user
    if @reply.save
      redirect_to motion_response_path(@comment.response), success: 'reply added successfully'
    else
      redirect_to motion_response_path(@comment.response)
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:description)
  end

  def fetch_comment
    @comment = Comment.find_by(id: params[:comment])
  end
end

app/controllers/motion/responses_controller.rb
class Motion::ResponsesController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_front, only: [:create, :update]
  before_action :fetch_response, only: [:show, :destroy]
  before_action :fetch_response_for_update, only: [:update]

  def show
    @front = @response.front
    @motion = @response.motion
    @all_responses = @front.responses.reject{ |r| r.id == @response.id }
    @comment = @response.comments.build(user: current_user)
    @reply = Reply.new
  end

  def create
    @response = Response.new(response_params)
    @response.front = @front
    @response.motion = @front.motion
    @response.user = current_user
    if @response.save
      redirect_to motion_path(@response.motion), success: 'Response added successfully'
    else
      redirect_to motion_path(@response.motion)
    end
  end

  def edit
  end

  def update
    if @response.user.id == current_user.id &&
        @response.front.id == @front.id &&
        @response.update(response_params)
      redirect_to motion_path(@response.motion), success: 'Response saved successfully'
    else
      redirect_to motion_path(@response.motion)
    end
  end

  def destroy
    motion = @response.motion
    @response.destroy
    redirect_to motion_path(motion), success: 'Response deleted successfully'
  end

  private

  def response_params
    params.require(:response).permit(:description)
  end

  def fetch_front
    @front = Front.find_by(id: params[:front])
  end

  def fetch_response
    @response = Response.find_by(id: params[:id])
  end

  def fetch_response_for_update
    @response = Response.find_by(id: params[:response][:id])
  end
end

app/views/motion/responses/_comments.html.erb
<div id="<%= "#{comment.user.username}-comment" %>" class="cmmnt">
  <%= comment.description.html_safe %>

  <% if comment.user.id == current_user.id %>
    <div class="right-icons">
      <div class="pull-right">
        <a class='btn-default btn-xs badge comment-edit-button' toggle-text="Hide">Edit</a>&nbsp;
      </div>
    </div>

    <div class="comment-edit-form">
      <%= render partial: '/motion/form_for_any_response', locals: { form_target: comment, target_url: motion_comments_path(response: response.id), target_method: :patch, submit_button_name: 'Update' } %>
    </div>
  <% else %>
    <div class="right-icons">
      <div class="pull-right">
        &nbsp;<%= link_to (comment.user.account_picture? ? image_tag(comment.user.account_picture_url(:thumb)) : image_tag('default-dp.png', width: 50)), users_account_path(u: comment.user.username) %>&nbsp;
      </div>
      <div class="pull-right">
        <span class="badge"><%= "#{comment.user.username}, #{comment.created_at.strftime('%B %d, %Y | %I:%M %p')}" %></span>
      </div>

      <div class="rating pull-right pull-up">
        <%= button_to motion_rating_path(comment_id: comment.id), remote: true, method: :post, class: "btn btn-xs btn-#{comment.rating.where(user: current_user).exists? ? 'warning' : 'default'}" do %>
          Upvote <span class="badge comment-<%= comment.id %>-upvote-count"><%= comment.rating.count %></span>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if @response.user.id == current_user.id %>
    <div class="right-icons">
      <div class="pull-right">
        <% unless comment.replies.exists? %>
          <a class='btn-default btn-xs badge comment-reply-button' toggle-text="Hide">Reply</a>&nbsp;
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<% if @response.user.id == current_user.id && !comment.replies.exists? %>
  <div class="reply comment-reply-form">
    <%= form_for(@reply, url: motion_replies_path(comment: comment.id), html: { method: :post, class: 'form-inline' }) do |f| %>
      <%= f.text_area :description, class: 'form-control input-sm', placeholder: 'Register your response', required: true, cols: 50 %>
      <%= f.submit 'Enter', class: 'btn btn-success btn-xs' %>
    <% end %>
  </div>
<% end %>

<% if comment.replies.exists? %>
<div class="reply">
  <% comment.replies.each do |r| %>
    <%= render partial: 'replies', locals: { reply: r, comment: comment } %>
  <% end %>
</div>
<% end %>

app/views/motion/responses/_replies.html.erb
<%= reply.description.html_safe %>

<% if reply.user.id == current_user.id %>
<div class="right-icons">
  <div class="pull-right">
     <a class='btn-default btn-xs badge reply-edit-button' toggle-text="Hide">Edit</a>&nbsp;
  </div>
</div>

<div class="reply-edit-form">
  <%= form_for(reply, url: motion_reply_path(comment: comment.id), html: { method: :patch, class: 'form-inline' }) do |f| %>
    <%= f.text_area :description, class: 'form-control input-sm', placeholder: 'Register your response', required: true, cols: 50 %>
    <%= f.submit 'Enter', class: 'btn btn-success btn-xs' %>
  <% end %>
</div>
<% else %>
<div class="right-icons">
  <div class="pull-right">
    &nbsp;<%= link_to (reply.user.account_picture? ? image_tag(reply.user.account_picture_url(:thumb)) : image_tag('default-dp.png', width: 50)), users_account_path(u: reply.user.username) %>&nbsp;
  </div>
  <div class="pull-right">
    <span class="badge">
      <%= "#{reply.user.username}, #{reply.created_at.strftime('%B %d, %Y | %I:%M %p')}" %>
    </span>
  </div>

  <div class="rating pull-right pull-up">
    <%= button_to motion_rating_path(reply_id: reply.id), remote: true, method: :post, class: "btn btn-xs btn-#{reply.rating.where(user: current_user).exists? ? 'warning' : 'default'}" do %>
      Upvote <span class="badge reply-<%= reply.id %>-upvote-count"><%= reply.rating.count %></span>
    <% end %>
  </div>
</div>
<% end %>

app/views/motion/responses/_responses.html.erb
  <% if current_user && response.user.id == current_user.id -%>
    <span class="pull-right">
      <div class="label label-info">Edit it at <%= link_to 'home page', motion_path(response.motion) %></div>
    </span>
    <span class="pull-right">
      <%= link_to 'View', motion_response_path(response), class: 'btn-default btn-xs badge' %>&nbsp;
    </span>

  <% else %>
    <div class="pull-right">
      &nbsp;
      <%= link_to (response.user.account_picture? ? image_tag(response.user.account_picture_url(:thumb)) : image_tag('default-dp.png', width: 50)), users_account_path(u: response.user.username) %>
      &nbsp;
    </div>
    <div class="pull-right">
      <span class="badge"><%= "#{response.user.username}, #{response.created_at.strftime('%B %d, %Y | %I:%M %p')}" %>
      </span>
    </div>
    <div class="pull-right">
      <%= link_to 'Intercept', motion_response_path(response), class: 'btn-default btn-xs badge' %>&nbsp;
    </div>

    <div class="rating pull-right pull-up">
      <%= button_to motion_rating_path(response_id: response.id), remote: true, method: :post, class: "btn btn-xs btn-#{response.rating.where(user: current_user).exists? ? 'warning' : 'default'}" do %>
        Upvote <span class="badge response-<%= response.id %>-upvote-count"><%= response.rating.count %></span>
      <% end %>
    </div>
  <% end -%>

<div class="content">
  <%= response.description.html_safe %>
</div>

app/views/motion/responses/edit.html.erb
<h2>Edit Page coming soon</h2>

<%= link_to "Back", :back %>

app/views/motion/responses/show.html.erb
<%= javascript_include_tag 'comment_reply_manager' %>
<%= javascript_include_tag 'edit_comment_manager' %>
<%= javascript_include_tag 'edit_reply_manager' %>

<h2>Response</h2>
<%= render partial: '/motion/motions', locals: { motion: @motion } %>

<div class="fronts">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
        <%= @front.name %>
      </h3>
    </div>
    <div class="panel-body response">
      <div class="pull-right">
        &nbsp;<%= link_to (@response.user.account_picture? ? image_tag(@response.user.account_picture_url(:thumb)) : image_tag('default-dp.png', width: 50)), users_account_path(u: @response.user.username) %>&nbsp;
      </div>
      <div class="pull-right">
        <span class="badge">
          <%= "#{@response.user.username}, #{@response.created_at.strftime('%B %d, %Y | %I:%M %p')}" %>
        </span>
      </div>
      <% if @response.user.id == current_user.id %>
        <div class="pull-right">
          <div class="label">
            <%= link_to 'Delete', motion_response_path(@response), method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: 'Are you sure?' } %>
          </div>
          <div class="label label-info">
            Edit it at <%= link_to 'home page', motion_path(@response.motion) %>
          </div>
        </div>
      <% else %>

        <div class="rating pull-right pull-up">
          <%= button_to motion_rating_path(response_id: @response.id), remote: true, method: :post, class: "btn btn-xs btn-#{@response.rating.where(user: current_user).exists? ? 'warning' : 'default'}" do %>
            Upvote <span class="badge reply-<%= @response.id %>-upvote-count"><%= @response.rating.count %></span>
          <% end %>
        </div>
      <% end %>

      <div class="content">
        <%= @response.description.html_safe %>
      </div>

      <div class="comments">
        <% if current_user && @response.comments.where(user: current_user).exists? %>
          <p class="label label-info">
            You have already registered your response. You can edit it <a href="#<%= "#{current_user.username}-comment" %>" class="">here</a>
          </p>
        <% elsif @response.user.id == current_user.id %>
          <p class="label label-info">You can't comment on your own response!</p>
        <% end %>

        <% if current_user && @response.user.id != current_user.id && !@response.comments.where(user: current_user).exists? %>
          <div class="cmmnt">
            <%= render partial: '/motion/form_for_any_response', locals: { form_target: @comment, target_url: motion_comments_path(response: @response.id), target_method: :post, submit_button_name: 'Enter' } %>
          </div>
        <% end %>

        <% @response.comments.reject{ |c| c.new_record? }.each do |c| %>
          <div class="comment-container">
            <%= render partial: 'comments', locals: { comment: c, response: @response } %>
          </div>
        <% end %>
      </div>

      <% @all_responses.each do |r| %>
        <%= render partial: 'responses', locals: { response: r } %>
      <% end %>
    </div>
  </div>
</div>